shell.run("rm", "update.lua")
shell.run("wget", "https://raw.githubusercontent.com/Kolterdyx/computercraft/master/putosSA/computer/home_system/update.lua")
term.clear()
term.setCursorPos(1,1)
shell.run("home")
